// Code generated by ent, DO NOT EDIT.

package review

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the review type in the database.
	Label = "review"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldReviewType holds the string denoting the review_type field in the database.
	FieldReviewType = "review_type"
	// FieldRating holds the string denoting the rating field in the database.
	FieldRating = "rating"
	// FieldComment holds the string denoting the comment field in the database.
	FieldComment = "comment"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// EdgeAd holds the string denoting the ad edge name in mutations.
	EdgeAd = "ad"
	// Table holds the table name of the review in the database.
	Table = "reviews"
	// AdTable is the table that holds the ad relation/edge.
	AdTable = "reviews"
	// AdInverseTable is the table name for the Ad entity.
	// It exists in this package in order to avoid circular dependency with the "ad" package.
	AdInverseTable = "ads"
	// AdColumn is the table column denoting the ad relation/edge.
	AdColumn = "ad_reviews"
)

// Columns holds all SQL columns for review fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldReviewType,
	FieldRating,
	FieldComment,
	FieldPhone,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "reviews"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"ad_reviews",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// RatingValidator is a validator for the "rating" field. It is called by the builders before save.
	RatingValidator func(int) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// ReviewType defines the type for the "review_type" enum field.
type ReviewType string

// ReviewType values.
const (
	ReviewTypeAd     ReviewType = "ad"
	ReviewTypeSeller ReviewType = "seller"
)

func (rt ReviewType) String() string {
	return string(rt)
}

// ReviewTypeValidator is a validator for the "review_type" field enum values. It is called by the builders before save.
func ReviewTypeValidator(rt ReviewType) error {
	switch rt {
	case ReviewTypeAd, ReviewTypeSeller:
		return nil
	default:
		return fmt.Errorf("review: invalid enum value for review_type field: %q", rt)
	}
}

// OrderOption defines the ordering options for the Review queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByReviewType orders the results by the review_type field.
func ByReviewType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewType, opts...).ToFunc()
}

// ByRating orders the results by the rating field.
func ByRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRating, opts...).ToFunc()
}

// ByComment orders the results by the comment field.
func ByComment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldComment, opts...).ToFunc()
}

// ByPhone orders the results by the phone field.
func ByPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhone, opts...).ToFunc()
}

// ByAdField orders the results by ad field.
func ByAdField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAdStep(), sql.OrderByField(field, opts...))
	}
}
func newAdStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AdInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AdTable, AdColumn),
	)
}
