-- atlas:pos ads[type=table] /Users/dan/code/go/missing-reviews/backend/internal/models/ad.go:14
-- atlas:pos reviews[type=table] /Users/dan/code/go/missing-reviews/backend/internal/models/review.go:14
-- atlas:pos sellers[type=table] /Users/dan/code/go/missing-reviews/backend/internal/models/seller.go:14
-- atlas:pos users[type=table] /Users/dan/code/go/missing-reviews/backend/internal/models/user.go:13

-- Create "sellers" table
CREATE TABLE "sellers" (
  "id" character varying NOT NULL,
  "create_time" timestamptz NOT NULL,
  "update_time" timestamptz NOT NULL,
  "name" character varying NULL,
  "phone" character varying NULL,
  "location" character varying NULL,
  "profile_url" character varying NULL,
  "average_rating" double precision NOT NULL DEFAULT 0,
  "review_count" bigint NOT NULL DEFAULT 0,
  "ad_count" bigint NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "seller_phone" to table: "sellers"
CREATE INDEX "seller_phone" ON "sellers" ("phone");
-- Create index "seller_profile_url" to table: "sellers"
CREATE INDEX "seller_profile_url" ON "sellers" ("profile_url");
-- Create index "seller_location" to table: "sellers"
CREATE INDEX "seller_location" ON "sellers" ("location");
-- Create index "seller_created_at" to table: "sellers"
CREATE INDEX "seller_created_at" ON "sellers" ("created_at");
-- Create "users" table
CREATE TABLE "users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "create_time" timestamptz NOT NULL,
  "update_time" timestamptz NOT NULL,
  "email" character varying NOT NULL,
  "password" character varying NOT NULL,
  "name" character varying NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "users" ("email");
-- Create index "user_email" to table: "users"
CREATE INDEX "user_email" ON "users" ("email");
-- Create "ads" table
CREATE TABLE "ads" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "create_time" timestamptz NOT NULL,
  "update_time" timestamptz NOT NULL,
  "url" character varying NOT NULL,
  "title" character varying NULL,
  "price" character varying NULL,
  "category" character varying NULL,
  "phone" character varying NULL,
  "average_rating" double precision NOT NULL DEFAULT 0,
  "review_count" bigint NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "seller_ads" character varying NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "ads_sellers_ads" FOREIGN KEY ("seller_ads") REFERENCES "sellers" ("id") ON DELETE SET NULL
);
-- Create index "ads_url_key" to table: "ads"
CREATE UNIQUE INDEX "ads_url_key" ON "ads" ("url");
-- Create index "ad_url" to table: "ads"
CREATE INDEX "ad_url" ON "ads" ("url");
-- Create index "ad_phone" to table: "ads"
CREATE INDEX "ad_phone" ON "ads" ("phone");
-- Create index "ad_category" to table: "ads"
CREATE INDEX "ad_category" ON "ads" ("category");
-- Create index "ad_created_at" to table: "ads"
CREATE INDEX "ad_created_at" ON "ads" ("created_at");
-- Create "reviews" table
CREATE TABLE "reviews" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "create_time" timestamptz NOT NULL,
  "update_time" timestamptz NOT NULL,
  "review_type" character varying NOT NULL,
  "rating" bigint NOT NULL,
  "comment" text NOT NULL,
  "phone" character varying NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "ad_reviews" bigint NULL,
  "seller_reviews" character varying NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "reviews_ads_reviews" FOREIGN KEY ("ad_reviews") REFERENCES "ads" ("id") ON DELETE SET NULL,
  CONSTRAINT "reviews_sellers_reviews" FOREIGN KEY ("seller_reviews") REFERENCES "sellers" ("id") ON DELETE SET NULL
);
-- Create index "review_review_type" to table: "reviews"
CREATE INDEX "review_review_type" ON "reviews" ("review_type");
-- Create index "review_phone" to table: "reviews"
CREATE INDEX "review_phone" ON "reviews" ("phone");
-- Create index "review_rating" to table: "reviews"
CREATE INDEX "review_rating" ON "reviews" ("rating");
-- Create index "review_created_at" to table: "reviews"
CREATE INDEX "review_created_at" ON "reviews" ("created_at");

