// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"time"
)

// NewAd creates a new Ad instance
func NewAd() *Ad {
	return &Ad{}
}

// NewSeller creates a new Seller instance
func NewSeller() *Seller {
	return &Seller{}
}

// NewReview creates a new Review instance
func NewReview() *Review {
	return &Review{}
}

// NewCreateReviewInput creates a new CreateReviewInput instance
func NewCreateReviewInput() *CreateReviewInput {
	return &CreateReviewInput{}
}

// Ad represents an advertisement
type Ad struct {
	ID            string    `json:"id"`
	URL           string    `json:"url"`
	Title         *string   `json:"title"`
	SellerID      *string   `json:"sellerId"`
	Phone         *string   `json:"phone"`
	AverageRating *float64  `json:"averageRating"`
	ReviewCount   *int      `json:"reviewCount"`
	Reviews       []*Review `json:"reviews"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

// Seller represents a seller
type Seller struct {
	ID            string    `json:"id"`
	Name          *string   `json:"name"`
	Phone         *string   `json:"phone"`
	AverageRating *float64  `json:"averageRating"`
	ReviewCount   *int      `json:"reviewCount"`
	Reviews       []*Review `json:"reviews"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

// Review represents a review
type Review struct {
	ID        string    `json:"id"`
	AdID      string    `json:"adId"`
	SellerID  *string   `json:"sellerId"`
	Phone     *string   `json:"phone"`
	Rating    int       `json:"rating"`
	Comment   string    `json:"comment"`
	CreatedAt time.Time `json:"createdAt"`
	Ad        *Ad       `json:"ad"`
	Seller    *Seller   `json:"seller"`
}

// CreateReviewInput represents input for creating a review
type CreateReviewInput struct {
	AdURL    string  `json:"adUrl"`
	AdTitle  *string `json:"adTitle"`
	SellerID *string `json:"sellerId"`
	Phone    *string `json:"phone"`
	Rating   int     `json:"rating"`
	Comment  string  `json:"comment"`
} 