// Code generated by ent, DO NOT EDIT.

package privacy

import (
	"context"

	"blindbuy-backend/internal"

	"entgo.io/ent/entql"
	"entgo.io/ent/privacy"
)

var (
	// Allow may be returned by rules to indicate that the policy
	// evaluation should terminate with allow decision.
	Allow = privacy.Allow

	// Deny may be returned by rules to indicate that the policy
	// evaluation should terminate with deny decision.
	Deny = privacy.Deny

	// Skip may be returned by rules to indicate that the policy
	// evaluation should continue to the next rule.
	Skip = privacy.Skip
)

// Allowf returns a formatted wrapped Allow decision.
func Allowf(format string, a ...any) error {
	return privacy.Allowf(format, a...)
}

// Denyf returns a formatted wrapped Deny decision.
func Denyf(format string, a ...any) error {
	return privacy.Denyf(format, a...)
}

// Skipf returns a formatted wrapped Skip decision.
func Skipf(format string, a ...any) error {
	return privacy.Skipf(format, a...)
}

// DecisionContext creates a new context from the given parent context with
// a policy decision attach to it.
func DecisionContext(parent context.Context, decision error) context.Context {
	return privacy.DecisionContext(parent, decision)
}

// DecisionFromContext retrieves the policy decision from the context.
func DecisionFromContext(ctx context.Context) (error, bool) {
	return privacy.DecisionFromContext(ctx)
}

type (
	// Policy groups query and mutation policies.
	Policy = privacy.Policy

	// QueryRule defines the interface deciding whether a
	// query is allowed and optionally modify it.
	QueryRule = privacy.QueryRule
	// QueryPolicy combines multiple query rules into a single policy.
	QueryPolicy = privacy.QueryPolicy

	// MutationRule defines the interface which decides whether a
	// mutation is allowed and optionally modifies it.
	MutationRule = privacy.MutationRule
	// MutationPolicy combines multiple mutation rules into a single policy.
	MutationPolicy = privacy.MutationPolicy
	// MutationRuleFunc type is an adapter which allows the use of
	// ordinary functions as mutation rules.
	MutationRuleFunc = privacy.MutationRuleFunc

	// QueryMutationRule is an interface which groups query and mutation rules.
	QueryMutationRule = privacy.QueryMutationRule
)

// QueryRuleFunc type is an adapter to allow the use of
// ordinary functions as query rules.
type QueryRuleFunc func(context.Context, internal.Query) error

// Eval returns f(ctx, q).
func (f QueryRuleFunc) EvalQuery(ctx context.Context, q internal.Query) error {
	return f(ctx, q)
}

// AlwaysAllowRule returns a rule that returns an allow decision.
func AlwaysAllowRule() QueryMutationRule {
	return privacy.AlwaysAllowRule()
}

// AlwaysDenyRule returns a rule that returns a deny decision.
func AlwaysDenyRule() QueryMutationRule {
	return privacy.AlwaysDenyRule()
}

// ContextQueryMutationRule creates a query/mutation rule from a context eval func.
func ContextQueryMutationRule(eval func(context.Context) error) QueryMutationRule {
	return privacy.ContextQueryMutationRule(eval)
}

// OnMutationOperation evaluates the given rule only on a given mutation operation.
func OnMutationOperation(rule MutationRule, op internal.Op) MutationRule {
	return privacy.OnMutationOperation(rule, op)
}

// DenyMutationOperationRule returns a rule denying specified mutation operation.
func DenyMutationOperationRule(op internal.Op) MutationRule {
	rule := MutationRuleFunc(func(_ context.Context, m internal.Mutation) error {
		return Denyf("internal/privacy: operation %s is not allowed", m.Op())
	})
	return OnMutationOperation(rule, op)
}

// The AdQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type AdQueryRuleFunc func(context.Context, *internal.AdQuery) error

// EvalQuery return f(ctx, q).
func (f AdQueryRuleFunc) EvalQuery(ctx context.Context, q internal.Query) error {
	if q, ok := q.(*internal.AdQuery); ok {
		return f(ctx, q)
	}
	return Denyf("internal/privacy: unexpected query type %T, expect *internal.AdQuery", q)
}

// The AdMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type AdMutationRuleFunc func(context.Context, *internal.AdMutation) error

// EvalMutation calls f(ctx, m).
func (f AdMutationRuleFunc) EvalMutation(ctx context.Context, m internal.Mutation) error {
	if m, ok := m.(*internal.AdMutation); ok {
		return f(ctx, m)
	}
	return Denyf("internal/privacy: unexpected mutation type %T, expect *internal.AdMutation", m)
}

// The ReviewQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type ReviewQueryRuleFunc func(context.Context, *internal.ReviewQuery) error

// EvalQuery return f(ctx, q).
func (f ReviewQueryRuleFunc) EvalQuery(ctx context.Context, q internal.Query) error {
	if q, ok := q.(*internal.ReviewQuery); ok {
		return f(ctx, q)
	}
	return Denyf("internal/privacy: unexpected query type %T, expect *internal.ReviewQuery", q)
}

// The ReviewMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type ReviewMutationRuleFunc func(context.Context, *internal.ReviewMutation) error

// EvalMutation calls f(ctx, m).
func (f ReviewMutationRuleFunc) EvalMutation(ctx context.Context, m internal.Mutation) error {
	if m, ok := m.(*internal.ReviewMutation); ok {
		return f(ctx, m)
	}
	return Denyf("internal/privacy: unexpected mutation type %T, expect *internal.ReviewMutation", m)
}

type (
	// Filter is the interface that wraps the Where function
	// for filtering nodes in queries and mutations.
	Filter interface {
		// Where applies a filter on the executed query/mutation.
		Where(entql.P)
	}

	// The FilterFunc type is an adapter that allows the use of ordinary
	// functions as filters for query and mutation types.
	FilterFunc func(context.Context, Filter) error
)

// EvalQuery calls f(ctx, q) if the query implements the Filter interface, otherwise it is denied.
func (f FilterFunc) EvalQuery(ctx context.Context, q internal.Query) error {
	fr, err := queryFilter(q)
	if err != nil {
		return err
	}
	return f(ctx, fr)
}

// EvalMutation calls f(ctx, q) if the mutation implements the Filter interface, otherwise it is denied.
func (f FilterFunc) EvalMutation(ctx context.Context, m internal.Mutation) error {
	fr, err := mutationFilter(m)
	if err != nil {
		return err
	}
	return f(ctx, fr)
}

var _ QueryMutationRule = FilterFunc(nil)

func queryFilter(q internal.Query) (Filter, error) {
	switch q := q.(type) {
	case *internal.AdQuery:
		return q.Filter(), nil
	case *internal.ReviewQuery:
		return q.Filter(), nil
	default:
		return nil, Denyf("internal/privacy: unexpected query type %T for query filter", q)
	}
}

func mutationFilter(m internal.Mutation) (Filter, error) {
	switch m := m.(type) {
	case *internal.AdMutation:
		return m.Filter(), nil
	case *internal.ReviewMutation:
		return m.Filter(), nil
	default:
		return nil, Denyf("internal/privacy: unexpected mutation type %T for mutation filter", m)
	}
}
