// Code generated by ent, DO NOT EDIT.

package internal

import (
	"blindbuy-backend/internal/ad"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Ad is the model entity for the Ad schema.
type Ad struct {
	config `json:"-"`
	// ID of the ent.
	// The unique identifier of the ad
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// The URL of the ad
	URL string `json:"url,omitempty"`
	// The title of the ad
	Title string `json:"title,omitempty"`
	// The price of the ad
	Price string `json:"price,omitempty"`
	// The category of the ad
	Category string `json:"category,omitempty"`
	// The phone number associated with the ad
	Phone string `json:"phone,omitempty"`
	// The average rating of the ad
	AverageRating float64 `json:"average_rating,omitempty"`
	// The number of reviews for the ad
	ReviewCount int `json:"review_count,omitempty"`
	// The creation timestamp
	CreatedAt time.Time `json:"created_at,omitempty"`
	// The last update timestamp
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AdQuery when eager-loading is set.
	Edges        AdEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AdEdges holds the relations/edges for other nodes in the graph.
type AdEdges struct {
	// The reviews for this ad
	Reviews []*Review `json:"reviews,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ReviewsOrErr returns the Reviews value or an error if the edge
// was not loaded in eager-loading.
func (e AdEdges) ReviewsOrErr() ([]*Review, error) {
	if e.loadedTypes[0] {
		return e.Reviews, nil
	}
	return nil, &NotLoadedError{edge: "reviews"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Ad) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ad.FieldAverageRating:
			values[i] = new(sql.NullFloat64)
		case ad.FieldID, ad.FieldReviewCount:
			values[i] = new(sql.NullInt64)
		case ad.FieldURL, ad.FieldTitle, ad.FieldPrice, ad.FieldCategory, ad.FieldPhone:
			values[i] = new(sql.NullString)
		case ad.FieldCreateTime, ad.FieldUpdateTime, ad.FieldCreatedAt, ad.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Ad fields.
func (_m *Ad) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ad.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case ad.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case ad.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case ad.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case ad.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case ad.FieldPrice:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				_m.Price = value.String
			}
		case ad.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case ad.FieldPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone", values[i])
			} else if value.Valid {
				_m.Phone = value.String
			}
		case ad.FieldAverageRating:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field average_rating", values[i])
			} else if value.Valid {
				_m.AverageRating = value.Float64
			}
		case ad.FieldReviewCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field review_count", values[i])
			} else if value.Valid {
				_m.ReviewCount = int(value.Int64)
			}
		case ad.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case ad.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Ad.
// This includes values selected through modifiers, order, etc.
func (_m *Ad) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryReviews queries the "reviews" edge of the Ad entity.
func (_m *Ad) QueryReviews() *ReviewQuery {
	return NewAdClient(_m.config).QueryReviews(_m)
}

// Update returns a builder for updating this Ad.
// Note that you need to call Ad.Unwrap() before calling this method if this Ad
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Ad) Update() *AdUpdateOne {
	return NewAdClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Ad entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Ad) Unwrap() *Ad {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("internal: Ad is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Ad) String() string {
	var builder strings.Builder
	builder.WriteString("Ad(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("price=")
	builder.WriteString(_m.Price)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	builder.WriteString("phone=")
	builder.WriteString(_m.Phone)
	builder.WriteString(", ")
	builder.WriteString("average_rating=")
	builder.WriteString(fmt.Sprintf("%v", _m.AverageRating))
	builder.WriteString(", ")
	builder.WriteString("review_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReviewCount))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Ads is a parsable slice of Ad.
type Ads []*Ad
