// Code generated by ent, DO NOT EDIT.

package internal

import (
	"blindbuy-backend/internal/ad"
	"blindbuy-backend/internal/review"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AdCreate is the builder for creating a Ad entity.
type AdCreate struct {
	config
	mutation *AdMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *AdCreate) SetCreateTime(v time.Time) *AdCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *AdCreate) SetNillableCreateTime(v *time.Time) *AdCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *AdCreate) SetUpdateTime(v time.Time) *AdCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *AdCreate) SetNillableUpdateTime(v *time.Time) *AdCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetURL sets the "url" field.
func (_c *AdCreate) SetURL(v string) *AdCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *AdCreate) SetTitle(v string) *AdCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *AdCreate) SetNillableTitle(v *string) *AdCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetPrice sets the "price" field.
func (_c *AdCreate) SetPrice(v string) *AdCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_c *AdCreate) SetNillablePrice(v *string) *AdCreate {
	if v != nil {
		_c.SetPrice(*v)
	}
	return _c
}

// SetCategory sets the "category" field.
func (_c *AdCreate) SetCategory(v string) *AdCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *AdCreate) SetNillableCategory(v *string) *AdCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetPhone sets the "phone" field.
func (_c *AdCreate) SetPhone(v string) *AdCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_c *AdCreate) SetNillablePhone(v *string) *AdCreate {
	if v != nil {
		_c.SetPhone(*v)
	}
	return _c
}

// SetAverageRating sets the "average_rating" field.
func (_c *AdCreate) SetAverageRating(v float64) *AdCreate {
	_c.mutation.SetAverageRating(v)
	return _c
}

// SetNillableAverageRating sets the "average_rating" field if the given value is not nil.
func (_c *AdCreate) SetNillableAverageRating(v *float64) *AdCreate {
	if v != nil {
		_c.SetAverageRating(*v)
	}
	return _c
}

// SetReviewCount sets the "review_count" field.
func (_c *AdCreate) SetReviewCount(v int) *AdCreate {
	_c.mutation.SetReviewCount(v)
	return _c
}

// SetNillableReviewCount sets the "review_count" field if the given value is not nil.
func (_c *AdCreate) SetNillableReviewCount(v *int) *AdCreate {
	if v != nil {
		_c.SetReviewCount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AdCreate) SetCreatedAt(v time.Time) *AdCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AdCreate) SetNillableCreatedAt(v *time.Time) *AdCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AdCreate) SetUpdatedAt(v time.Time) *AdCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AdCreate) SetNillableUpdatedAt(v *time.Time) *AdCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AdCreate) SetID(v int) *AdCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddReviewIDs adds the "reviews" edge to the Review entity by IDs.
func (_c *AdCreate) AddReviewIDs(ids ...int) *AdCreate {
	_c.mutation.AddReviewIDs(ids...)
	return _c
}

// AddReviews adds the "reviews" edges to the Review entity.
func (_c *AdCreate) AddReviews(v ...*Review) *AdCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddReviewIDs(ids...)
}

// Mutation returns the AdMutation object of the builder.
func (_c *AdCreate) Mutation() *AdMutation {
	return _c.mutation
}

// Save creates the Ad in the database.
func (_c *AdCreate) Save(ctx context.Context) (*Ad, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AdCreate) SaveX(ctx context.Context) *Ad {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AdCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := ad.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := ad.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.AverageRating(); !ok {
		v := ad.DefaultAverageRating
		_c.mutation.SetAverageRating(v)
	}
	if _, ok := _c.mutation.ReviewCount(); !ok {
		v := ad.DefaultReviewCount
		_c.mutation.SetReviewCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ad.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ad.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AdCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`internal: missing required field "Ad.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`internal: missing required field "Ad.update_time"`)}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`internal: missing required field "Ad.url"`)}
	}
	if _, ok := _c.mutation.AverageRating(); !ok {
		return &ValidationError{Name: "average_rating", err: errors.New(`internal: missing required field "Ad.average_rating"`)}
	}
	if _, ok := _c.mutation.ReviewCount(); !ok {
		return &ValidationError{Name: "review_count", err: errors.New(`internal: missing required field "Ad.review_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`internal: missing required field "Ad.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`internal: missing required field "Ad.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := ad.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`internal: validator failed for field "Ad.id": %w`, err)}
		}
	}
	return nil
}

func (_c *AdCreate) sqlSave(ctx context.Context) (*Ad, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AdCreate) createSpec() (*Ad, *sqlgraph.CreateSpec) {
	var (
		_node = &Ad{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ad.Table, sqlgraph.NewFieldSpec(ad.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(ad.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(ad.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(ad.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(ad.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(ad.FieldPrice, field.TypeString, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(ad.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(ad.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := _c.mutation.AverageRating(); ok {
		_spec.SetField(ad.FieldAverageRating, field.TypeFloat64, value)
		_node.AverageRating = value
	}
	if value, ok := _c.mutation.ReviewCount(); ok {
		_spec.SetField(ad.FieldReviewCount, field.TypeInt, value)
		_node.ReviewCount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ad.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ad.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ReviewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ad.ReviewsTable,
			Columns: []string{ad.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AdCreateBulk is the builder for creating many Ad entities in bulk.
type AdCreateBulk struct {
	config
	err      error
	builders []*AdCreate
}

// Save creates the Ad entities in the database.
func (_c *AdCreateBulk) Save(ctx context.Context) ([]*Ad, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Ad, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AdCreateBulk) SaveX(ctx context.Context) []*Ad {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
