// Code generated by ent, DO NOT EDIT.

package internal

import (
	"blindbuy-backend/internal/ad"
	"blindbuy-backend/internal/predicate"
	"blindbuy-backend/internal/review"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AdUpdate is the builder for updating Ad entities.
type AdUpdate struct {
	config
	hooks    []Hook
	mutation *AdMutation
}

// Where appends a list predicates to the AdUpdate builder.
func (_u *AdUpdate) Where(ps ...predicate.Ad) *AdUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *AdUpdate) SetUpdateTime(v time.Time) *AdUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetURL sets the "url" field.
func (_u *AdUpdate) SetURL(v string) *AdUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *AdUpdate) SetNillableURL(v *string) *AdUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *AdUpdate) SetTitle(v string) *AdUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *AdUpdate) SetNillableTitle(v *string) *AdUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *AdUpdate) ClearTitle() *AdUpdate {
	_u.mutation.ClearTitle()
	return _u
}

// SetPrice sets the "price" field.
func (_u *AdUpdate) SetPrice(v string) *AdUpdate {
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *AdUpdate) SetNillablePrice(v *string) *AdUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// ClearPrice clears the value of the "price" field.
func (_u *AdUpdate) ClearPrice() *AdUpdate {
	_u.mutation.ClearPrice()
	return _u
}

// SetCategory sets the "category" field.
func (_u *AdUpdate) SetCategory(v string) *AdUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *AdUpdate) SetNillableCategory(v *string) *AdUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *AdUpdate) ClearCategory() *AdUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// SetPhone sets the "phone" field.
func (_u *AdUpdate) SetPhone(v string) *AdUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *AdUpdate) SetNillablePhone(v *string) *AdUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *AdUpdate) ClearPhone() *AdUpdate {
	_u.mutation.ClearPhone()
	return _u
}

// SetAverageRating sets the "average_rating" field.
func (_u *AdUpdate) SetAverageRating(v float64) *AdUpdate {
	_u.mutation.ResetAverageRating()
	_u.mutation.SetAverageRating(v)
	return _u
}

// SetNillableAverageRating sets the "average_rating" field if the given value is not nil.
func (_u *AdUpdate) SetNillableAverageRating(v *float64) *AdUpdate {
	if v != nil {
		_u.SetAverageRating(*v)
	}
	return _u
}

// AddAverageRating adds value to the "average_rating" field.
func (_u *AdUpdate) AddAverageRating(v float64) *AdUpdate {
	_u.mutation.AddAverageRating(v)
	return _u
}

// SetReviewCount sets the "review_count" field.
func (_u *AdUpdate) SetReviewCount(v int) *AdUpdate {
	_u.mutation.ResetReviewCount()
	_u.mutation.SetReviewCount(v)
	return _u
}

// SetNillableReviewCount sets the "review_count" field if the given value is not nil.
func (_u *AdUpdate) SetNillableReviewCount(v *int) *AdUpdate {
	if v != nil {
		_u.SetReviewCount(*v)
	}
	return _u
}

// AddReviewCount adds value to the "review_count" field.
func (_u *AdUpdate) AddReviewCount(v int) *AdUpdate {
	_u.mutation.AddReviewCount(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AdUpdate) SetCreatedAt(v time.Time) *AdUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AdUpdate) SetNillableCreatedAt(v *time.Time) *AdUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdUpdate) SetUpdatedAt(v time.Time) *AdUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddReviewIDs adds the "reviews" edge to the Review entity by IDs.
func (_u *AdUpdate) AddReviewIDs(ids ...int) *AdUpdate {
	_u.mutation.AddReviewIDs(ids...)
	return _u
}

// AddReviews adds the "reviews" edges to the Review entity.
func (_u *AdUpdate) AddReviews(v ...*Review) *AdUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReviewIDs(ids...)
}

// Mutation returns the AdMutation object of the builder.
func (_u *AdUpdate) Mutation() *AdMutation {
	return _u.mutation
}

// ClearReviews clears all "reviews" edges to the Review entity.
func (_u *AdUpdate) ClearReviews() *AdUpdate {
	_u.mutation.ClearReviews()
	return _u
}

// RemoveReviewIDs removes the "reviews" edge to Review entities by IDs.
func (_u *AdUpdate) RemoveReviewIDs(ids ...int) *AdUpdate {
	_u.mutation.RemoveReviewIDs(ids...)
	return _u
}

// RemoveReviews removes "reviews" edges to Review entities.
func (_u *AdUpdate) RemoveReviews(v ...*Review) *AdUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReviewIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := ad.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ad.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AdUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(ad.Table, ad.Columns, sqlgraph.NewFieldSpec(ad.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(ad.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(ad.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(ad.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(ad.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(ad.FieldPrice, field.TypeString, value)
	}
	if _u.mutation.PriceCleared() {
		_spec.ClearField(ad.FieldPrice, field.TypeString)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(ad.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(ad.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(ad.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(ad.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.AverageRating(); ok {
		_spec.SetField(ad.FieldAverageRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAverageRating(); ok {
		_spec.AddField(ad.FieldAverageRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ReviewCount(); ok {
		_spec.SetField(ad.FieldReviewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReviewCount(); ok {
		_spec.AddField(ad.FieldReviewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(ad.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ad.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ad.ReviewsTable,
			Columns: []string{ad.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReviewsIDs(); len(nodes) > 0 && !_u.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ad.ReviewsTable,
			Columns: []string{ad.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ad.ReviewsTable,
			Columns: []string{ad.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ad.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdUpdateOne is the builder for updating a single Ad entity.
type AdUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *AdUpdateOne) SetUpdateTime(v time.Time) *AdUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetURL sets the "url" field.
func (_u *AdUpdateOne) SetURL(v string) *AdUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *AdUpdateOne) SetNillableURL(v *string) *AdUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *AdUpdateOne) SetTitle(v string) *AdUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *AdUpdateOne) SetNillableTitle(v *string) *AdUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *AdUpdateOne) ClearTitle() *AdUpdateOne {
	_u.mutation.ClearTitle()
	return _u
}

// SetPrice sets the "price" field.
func (_u *AdUpdateOne) SetPrice(v string) *AdUpdateOne {
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *AdUpdateOne) SetNillablePrice(v *string) *AdUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// ClearPrice clears the value of the "price" field.
func (_u *AdUpdateOne) ClearPrice() *AdUpdateOne {
	_u.mutation.ClearPrice()
	return _u
}

// SetCategory sets the "category" field.
func (_u *AdUpdateOne) SetCategory(v string) *AdUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *AdUpdateOne) SetNillableCategory(v *string) *AdUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *AdUpdateOne) ClearCategory() *AdUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// SetPhone sets the "phone" field.
func (_u *AdUpdateOne) SetPhone(v string) *AdUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *AdUpdateOne) SetNillablePhone(v *string) *AdUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *AdUpdateOne) ClearPhone() *AdUpdateOne {
	_u.mutation.ClearPhone()
	return _u
}

// SetAverageRating sets the "average_rating" field.
func (_u *AdUpdateOne) SetAverageRating(v float64) *AdUpdateOne {
	_u.mutation.ResetAverageRating()
	_u.mutation.SetAverageRating(v)
	return _u
}

// SetNillableAverageRating sets the "average_rating" field if the given value is not nil.
func (_u *AdUpdateOne) SetNillableAverageRating(v *float64) *AdUpdateOne {
	if v != nil {
		_u.SetAverageRating(*v)
	}
	return _u
}

// AddAverageRating adds value to the "average_rating" field.
func (_u *AdUpdateOne) AddAverageRating(v float64) *AdUpdateOne {
	_u.mutation.AddAverageRating(v)
	return _u
}

// SetReviewCount sets the "review_count" field.
func (_u *AdUpdateOne) SetReviewCount(v int) *AdUpdateOne {
	_u.mutation.ResetReviewCount()
	_u.mutation.SetReviewCount(v)
	return _u
}

// SetNillableReviewCount sets the "review_count" field if the given value is not nil.
func (_u *AdUpdateOne) SetNillableReviewCount(v *int) *AdUpdateOne {
	if v != nil {
		_u.SetReviewCount(*v)
	}
	return _u
}

// AddReviewCount adds value to the "review_count" field.
func (_u *AdUpdateOne) AddReviewCount(v int) *AdUpdateOne {
	_u.mutation.AddReviewCount(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AdUpdateOne) SetCreatedAt(v time.Time) *AdUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AdUpdateOne) SetNillableCreatedAt(v *time.Time) *AdUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdUpdateOne) SetUpdatedAt(v time.Time) *AdUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddReviewIDs adds the "reviews" edge to the Review entity by IDs.
func (_u *AdUpdateOne) AddReviewIDs(ids ...int) *AdUpdateOne {
	_u.mutation.AddReviewIDs(ids...)
	return _u
}

// AddReviews adds the "reviews" edges to the Review entity.
func (_u *AdUpdateOne) AddReviews(v ...*Review) *AdUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReviewIDs(ids...)
}

// Mutation returns the AdMutation object of the builder.
func (_u *AdUpdateOne) Mutation() *AdMutation {
	return _u.mutation
}

// ClearReviews clears all "reviews" edges to the Review entity.
func (_u *AdUpdateOne) ClearReviews() *AdUpdateOne {
	_u.mutation.ClearReviews()
	return _u
}

// RemoveReviewIDs removes the "reviews" edge to Review entities by IDs.
func (_u *AdUpdateOne) RemoveReviewIDs(ids ...int) *AdUpdateOne {
	_u.mutation.RemoveReviewIDs(ids...)
	return _u
}

// RemoveReviews removes "reviews" edges to Review entities.
func (_u *AdUpdateOne) RemoveReviews(v ...*Review) *AdUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReviewIDs(ids...)
}

// Where appends a list predicates to the AdUpdate builder.
func (_u *AdUpdateOne) Where(ps ...predicate.Ad) *AdUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdUpdateOne) Select(field string, fields ...string) *AdUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Ad entity.
func (_u *AdUpdateOne) Save(ctx context.Context) (*Ad, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdUpdateOne) SaveX(ctx context.Context) *Ad {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := ad.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ad.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AdUpdateOne) sqlSave(ctx context.Context) (_node *Ad, err error) {
	_spec := sqlgraph.NewUpdateSpec(ad.Table, ad.Columns, sqlgraph.NewFieldSpec(ad.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`internal: missing "Ad.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ad.FieldID)
		for _, f := range fields {
			if !ad.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("internal: invalid field %q for query", f)}
			}
			if f != ad.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(ad.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(ad.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(ad.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(ad.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(ad.FieldPrice, field.TypeString, value)
	}
	if _u.mutation.PriceCleared() {
		_spec.ClearField(ad.FieldPrice, field.TypeString)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(ad.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(ad.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(ad.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(ad.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.AverageRating(); ok {
		_spec.SetField(ad.FieldAverageRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAverageRating(); ok {
		_spec.AddField(ad.FieldAverageRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ReviewCount(); ok {
		_spec.SetField(ad.FieldReviewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReviewCount(); ok {
		_spec.AddField(ad.FieldReviewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(ad.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ad.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ad.ReviewsTable,
			Columns: []string{ad.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReviewsIDs(); len(nodes) > 0 && !_u.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ad.ReviewsTable,
			Columns: []string{ad.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ad.ReviewsTable,
			Columns: []string{ad.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Ad{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ad.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
