// Code generated by ent, DO NOT EDIT.

package internal

import (
	"blindbuy-backend/internal/ad"
	"blindbuy-backend/internal/predicate"
	"blindbuy-backend/internal/review"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
	"entgo.io/ent/schema/field"
)

// schemaGraph holds a representation of ent/schema at runtime.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 2)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   ad.Table,
			Columns: ad.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: ad.FieldID,
			},
		},
		Type: "Ad",
		Fields: map[string]*sqlgraph.FieldSpec{
			ad.FieldCreateTime:    {Type: field.TypeTime, Column: ad.FieldCreateTime},
			ad.FieldUpdateTime:    {Type: field.TypeTime, Column: ad.FieldUpdateTime},
			ad.FieldURL:           {Type: field.TypeString, Column: ad.FieldURL},
			ad.FieldTitle:         {Type: field.TypeString, Column: ad.FieldTitle},
			ad.FieldPrice:         {Type: field.TypeString, Column: ad.FieldPrice},
			ad.FieldCategory:      {Type: field.TypeString, Column: ad.FieldCategory},
			ad.FieldPhone:         {Type: field.TypeString, Column: ad.FieldPhone},
			ad.FieldAverageRating: {Type: field.TypeFloat64, Column: ad.FieldAverageRating},
			ad.FieldReviewCount:   {Type: field.TypeInt, Column: ad.FieldReviewCount},
			ad.FieldCreatedAt:     {Type: field.TypeTime, Column: ad.FieldCreatedAt},
			ad.FieldUpdatedAt:     {Type: field.TypeTime, Column: ad.FieldUpdatedAt},
		},
	}
	graph.Nodes[1] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   review.Table,
			Columns: review.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: review.FieldID,
			},
		},
		Type: "Review",
		Fields: map[string]*sqlgraph.FieldSpec{
			review.FieldCreateTime: {Type: field.TypeTime, Column: review.FieldCreateTime},
			review.FieldUpdateTime: {Type: field.TypeTime, Column: review.FieldUpdateTime},
			review.FieldReviewType: {Type: field.TypeEnum, Column: review.FieldReviewType},
			review.FieldRating:     {Type: field.TypeInt, Column: review.FieldRating},
			review.FieldComment:    {Type: field.TypeString, Column: review.FieldComment},
			review.FieldPhone:      {Type: field.TypeString, Column: review.FieldPhone},
		},
	}
	graph.MustAddE(
		"reviews",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ad.ReviewsTable,
			Columns: []string{ad.ReviewsColumn},
			Bidi:    false,
		},
		"Ad",
		"Review",
	)
	graph.MustAddE(
		"ad",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.AdTable,
			Columns: []string{review.AdColumn},
			Bidi:    false,
		},
		"Review",
		"Ad",
	)
	return graph
}()

// predicateAdder wraps the addPredicate method.
// All update, update-one and query builders implement this interface.
type predicateAdder interface {
	addPredicate(func(s *sql.Selector))
}

// addPredicate implements the predicateAdder interface.
func (_q *AdQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the AdQuery builder.
func (_q *AdQuery) Filter() *AdFilter {
	return &AdFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *AdMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the AdMutation builder.
func (m *AdMutation) Filter() *AdFilter {
	return &AdFilter{config: m.config, predicateAdder: m}
}

// AdFilter provides a generic filtering capability at runtime for AdQuery.
type AdFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *AdFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[0].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int predicate on the id field.
func (f *AdFilter) WhereID(p entql.IntP) {
	f.Where(p.Field(ad.FieldID))
}

// WhereCreateTime applies the entql time.Time predicate on the create_time field.
func (f *AdFilter) WhereCreateTime(p entql.TimeP) {
	f.Where(p.Field(ad.FieldCreateTime))
}

// WhereUpdateTime applies the entql time.Time predicate on the update_time field.
func (f *AdFilter) WhereUpdateTime(p entql.TimeP) {
	f.Where(p.Field(ad.FieldUpdateTime))
}

// WhereURL applies the entql string predicate on the url field.
func (f *AdFilter) WhereURL(p entql.StringP) {
	f.Where(p.Field(ad.FieldURL))
}

// WhereTitle applies the entql string predicate on the title field.
func (f *AdFilter) WhereTitle(p entql.StringP) {
	f.Where(p.Field(ad.FieldTitle))
}

// WherePrice applies the entql string predicate on the price field.
func (f *AdFilter) WherePrice(p entql.StringP) {
	f.Where(p.Field(ad.FieldPrice))
}

// WhereCategory applies the entql string predicate on the category field.
func (f *AdFilter) WhereCategory(p entql.StringP) {
	f.Where(p.Field(ad.FieldCategory))
}

// WherePhone applies the entql string predicate on the phone field.
func (f *AdFilter) WherePhone(p entql.StringP) {
	f.Where(p.Field(ad.FieldPhone))
}

// WhereAverageRating applies the entql float64 predicate on the average_rating field.
func (f *AdFilter) WhereAverageRating(p entql.Float64P) {
	f.Where(p.Field(ad.FieldAverageRating))
}

// WhereReviewCount applies the entql int predicate on the review_count field.
func (f *AdFilter) WhereReviewCount(p entql.IntP) {
	f.Where(p.Field(ad.FieldReviewCount))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *AdFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(ad.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *AdFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(ad.FieldUpdatedAt))
}

// WhereHasReviews applies a predicate to check if query has an edge reviews.
func (f *AdFilter) WhereHasReviews() {
	f.Where(entql.HasEdge("reviews"))
}

// WhereHasReviewsWith applies a predicate to check if query has an edge reviews with a given conditions (other predicates).
func (f *AdFilter) WhereHasReviewsWith(preds ...predicate.Review) {
	f.Where(entql.HasEdgeWith("reviews", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (_q *ReviewQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the ReviewQuery builder.
func (_q *ReviewQuery) Filter() *ReviewFilter {
	return &ReviewFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *ReviewMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the ReviewMutation builder.
func (m *ReviewMutation) Filter() *ReviewFilter {
	return &ReviewFilter{config: m.config, predicateAdder: m}
}

// ReviewFilter provides a generic filtering capability at runtime for ReviewQuery.
type ReviewFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *ReviewFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[1].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int predicate on the id field.
func (f *ReviewFilter) WhereID(p entql.IntP) {
	f.Where(p.Field(review.FieldID))
}

// WhereCreateTime applies the entql time.Time predicate on the create_time field.
func (f *ReviewFilter) WhereCreateTime(p entql.TimeP) {
	f.Where(p.Field(review.FieldCreateTime))
}

// WhereUpdateTime applies the entql time.Time predicate on the update_time field.
func (f *ReviewFilter) WhereUpdateTime(p entql.TimeP) {
	f.Where(p.Field(review.FieldUpdateTime))
}

// WhereReviewType applies the entql string predicate on the review_type field.
func (f *ReviewFilter) WhereReviewType(p entql.StringP) {
	f.Where(p.Field(review.FieldReviewType))
}

// WhereRating applies the entql int predicate on the rating field.
func (f *ReviewFilter) WhereRating(p entql.IntP) {
	f.Where(p.Field(review.FieldRating))
}

// WhereComment applies the entql string predicate on the comment field.
func (f *ReviewFilter) WhereComment(p entql.StringP) {
	f.Where(p.Field(review.FieldComment))
}

// WherePhone applies the entql string predicate on the phone field.
func (f *ReviewFilter) WherePhone(p entql.StringP) {
	f.Where(p.Field(review.FieldPhone))
}

// WhereHasAd applies a predicate to check if query has an edge ad.
func (f *ReviewFilter) WhereHasAd() {
	f.Where(entql.HasEdge("ad"))
}

// WhereHasAdWith applies a predicate to check if query has an edge ad with a given conditions (other predicates).
func (f *ReviewFilter) WhereHasAdWith(preds ...predicate.Ad) {
	f.Where(entql.HasEdgeWith("ad", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}
