// Code generated by ent, DO NOT EDIT.

package internal

import (
	"blindbuy-backend/internal/ad"
	"blindbuy-backend/internal/review"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Review is the model entity for the Review schema.
type Review struct {
	config `json:"-"`
	// ID of the ent.
	// The unique identifier of the review
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// The type of review (ad or seller)
	ReviewType review.ReviewType `json:"review_type,omitempty"`
	// The rating (1-5)
	Rating int `json:"rating,omitempty"`
	// The review comment
	Comment string `json:"comment,omitempty"`
	// The phone number of the reviewer
	Phone string `json:"phone,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReviewQuery when eager-loading is set.
	Edges        ReviewEdges `json:"edges"`
	ad_reviews   *int
	selectValues sql.SelectValues
}

// ReviewEdges holds the relations/edges for other nodes in the graph.
type ReviewEdges struct {
	// The ad this review belongs to
	Ad *Ad `json:"ad,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AdOrErr returns the Ad value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReviewEdges) AdOrErr() (*Ad, error) {
	if e.Ad != nil {
		return e.Ad, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: ad.Label}
	}
	return nil, &NotLoadedError{edge: "ad"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Review) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case review.FieldID, review.FieldRating:
			values[i] = new(sql.NullInt64)
		case review.FieldReviewType, review.FieldComment, review.FieldPhone:
			values[i] = new(sql.NullString)
		case review.FieldCreateTime, review.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case review.ForeignKeys[0]: // ad_reviews
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Review fields.
func (_m *Review) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case review.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case review.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case review.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case review.FieldReviewType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field review_type", values[i])
			} else if value.Valid {
				_m.ReviewType = review.ReviewType(value.String)
			}
		case review.FieldRating:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rating", values[i])
			} else if value.Valid {
				_m.Rating = int(value.Int64)
			}
		case review.FieldComment:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field comment", values[i])
			} else if value.Valid {
				_m.Comment = value.String
			}
		case review.FieldPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone", values[i])
			} else if value.Valid {
				_m.Phone = value.String
			}
		case review.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field ad_reviews", value)
			} else if value.Valid {
				_m.ad_reviews = new(int)
				*_m.ad_reviews = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Review.
// This includes values selected through modifiers, order, etc.
func (_m *Review) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAd queries the "ad" edge of the Review entity.
func (_m *Review) QueryAd() *AdQuery {
	return NewReviewClient(_m.config).QueryAd(_m)
}

// Update returns a builder for updating this Review.
// Note that you need to call Review.Unwrap() before calling this method if this Review
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Review) Update() *ReviewUpdateOne {
	return NewReviewClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Review entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Review) Unwrap() *Review {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("internal: Review is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Review) String() string {
	var builder strings.Builder
	builder.WriteString("Review(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("review_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReviewType))
	builder.WriteString(", ")
	builder.WriteString("rating=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rating))
	builder.WriteString(", ")
	builder.WriteString("comment=")
	builder.WriteString(_m.Comment)
	builder.WriteString(", ")
	builder.WriteString("phone=")
	builder.WriteString(_m.Phone)
	builder.WriteByte(')')
	return builder.String()
}

// Reviews is a parsable slice of Review.
type Reviews []*Review
