// Code generated by ent, DO NOT EDIT.

package internal

import (
	"blindbuy-backend/internal/ad"
	"blindbuy-backend/internal/predicate"
	"blindbuy-backend/internal/review"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ReviewUpdate is the builder for updating Review entities.
type ReviewUpdate struct {
	config
	hooks    []Hook
	mutation *ReviewMutation
}

// Where appends a list predicates to the ReviewUpdate builder.
func (_u *ReviewUpdate) Where(ps ...predicate.Review) *ReviewUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *ReviewUpdate) SetUpdateTime(v time.Time) *ReviewUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetReviewType sets the "review_type" field.
func (_u *ReviewUpdate) SetReviewType(v review.ReviewType) *ReviewUpdate {
	_u.mutation.SetReviewType(v)
	return _u
}

// SetNillableReviewType sets the "review_type" field if the given value is not nil.
func (_u *ReviewUpdate) SetNillableReviewType(v *review.ReviewType) *ReviewUpdate {
	if v != nil {
		_u.SetReviewType(*v)
	}
	return _u
}

// SetRating sets the "rating" field.
func (_u *ReviewUpdate) SetRating(v int) *ReviewUpdate {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *ReviewUpdate) SetNillableRating(v *int) *ReviewUpdate {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *ReviewUpdate) AddRating(v int) *ReviewUpdate {
	_u.mutation.AddRating(v)
	return _u
}

// SetComment sets the "comment" field.
func (_u *ReviewUpdate) SetComment(v string) *ReviewUpdate {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *ReviewUpdate) SetNillableComment(v *string) *ReviewUpdate {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *ReviewUpdate) SetPhone(v string) *ReviewUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *ReviewUpdate) SetNillablePhone(v *string) *ReviewUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *ReviewUpdate) ClearPhone() *ReviewUpdate {
	_u.mutation.ClearPhone()
	return _u
}

// SetAdID sets the "ad" edge to the Ad entity by ID.
func (_u *ReviewUpdate) SetAdID(id int) *ReviewUpdate {
	_u.mutation.SetAdID(id)
	return _u
}

// SetNillableAdID sets the "ad" edge to the Ad entity by ID if the given value is not nil.
func (_u *ReviewUpdate) SetNillableAdID(id *int) *ReviewUpdate {
	if id != nil {
		_u = _u.SetAdID(*id)
	}
	return _u
}

// SetAd sets the "ad" edge to the Ad entity.
func (_u *ReviewUpdate) SetAd(v *Ad) *ReviewUpdate {
	return _u.SetAdID(v.ID)
}

// Mutation returns the ReviewMutation object of the builder.
func (_u *ReviewUpdate) Mutation() *ReviewMutation {
	return _u.mutation
}

// ClearAd clears the "ad" edge to the Ad entity.
func (_u *ReviewUpdate) ClearAd() *ReviewUpdate {
	_u.mutation.ClearAd()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReviewUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReviewUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReviewUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReviewUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReviewUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := review.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReviewUpdate) check() error {
	if v, ok := _u.mutation.ReviewType(); ok {
		if err := review.ReviewTypeValidator(v); err != nil {
			return &ValidationError{Name: "review_type", err: fmt.Errorf(`internal: validator failed for field "Review.review_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Rating(); ok {
		if err := review.RatingValidator(v); err != nil {
			return &ValidationError{Name: "rating", err: fmt.Errorf(`internal: validator failed for field "Review.rating": %w`, err)}
		}
	}
	return nil
}

func (_u *ReviewUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(review.Table, review.Columns, sqlgraph.NewFieldSpec(review.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(review.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReviewType(); ok {
		_spec.SetField(review.FieldReviewType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(review.FieldRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(review.FieldRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(review.FieldComment, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(review.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(review.FieldPhone, field.TypeString)
	}
	if _u.mutation.AdCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.AdTable,
			Columns: []string{review.AdColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ad.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.AdTable,
			Columns: []string{review.AdColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ad.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{review.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReviewUpdateOne is the builder for updating a single Review entity.
type ReviewUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReviewMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *ReviewUpdateOne) SetUpdateTime(v time.Time) *ReviewUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetReviewType sets the "review_type" field.
func (_u *ReviewUpdateOne) SetReviewType(v review.ReviewType) *ReviewUpdateOne {
	_u.mutation.SetReviewType(v)
	return _u
}

// SetNillableReviewType sets the "review_type" field if the given value is not nil.
func (_u *ReviewUpdateOne) SetNillableReviewType(v *review.ReviewType) *ReviewUpdateOne {
	if v != nil {
		_u.SetReviewType(*v)
	}
	return _u
}

// SetRating sets the "rating" field.
func (_u *ReviewUpdateOne) SetRating(v int) *ReviewUpdateOne {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *ReviewUpdateOne) SetNillableRating(v *int) *ReviewUpdateOne {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *ReviewUpdateOne) AddRating(v int) *ReviewUpdateOne {
	_u.mutation.AddRating(v)
	return _u
}

// SetComment sets the "comment" field.
func (_u *ReviewUpdateOne) SetComment(v string) *ReviewUpdateOne {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *ReviewUpdateOne) SetNillableComment(v *string) *ReviewUpdateOne {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *ReviewUpdateOne) SetPhone(v string) *ReviewUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *ReviewUpdateOne) SetNillablePhone(v *string) *ReviewUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *ReviewUpdateOne) ClearPhone() *ReviewUpdateOne {
	_u.mutation.ClearPhone()
	return _u
}

// SetAdID sets the "ad" edge to the Ad entity by ID.
func (_u *ReviewUpdateOne) SetAdID(id int) *ReviewUpdateOne {
	_u.mutation.SetAdID(id)
	return _u
}

// SetNillableAdID sets the "ad" edge to the Ad entity by ID if the given value is not nil.
func (_u *ReviewUpdateOne) SetNillableAdID(id *int) *ReviewUpdateOne {
	if id != nil {
		_u = _u.SetAdID(*id)
	}
	return _u
}

// SetAd sets the "ad" edge to the Ad entity.
func (_u *ReviewUpdateOne) SetAd(v *Ad) *ReviewUpdateOne {
	return _u.SetAdID(v.ID)
}

// Mutation returns the ReviewMutation object of the builder.
func (_u *ReviewUpdateOne) Mutation() *ReviewMutation {
	return _u.mutation
}

// ClearAd clears the "ad" edge to the Ad entity.
func (_u *ReviewUpdateOne) ClearAd() *ReviewUpdateOne {
	_u.mutation.ClearAd()
	return _u
}

// Where appends a list predicates to the ReviewUpdate builder.
func (_u *ReviewUpdateOne) Where(ps ...predicate.Review) *ReviewUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReviewUpdateOne) Select(field string, fields ...string) *ReviewUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Review entity.
func (_u *ReviewUpdateOne) Save(ctx context.Context) (*Review, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReviewUpdateOne) SaveX(ctx context.Context) *Review {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReviewUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReviewUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReviewUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := review.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReviewUpdateOne) check() error {
	if v, ok := _u.mutation.ReviewType(); ok {
		if err := review.ReviewTypeValidator(v); err != nil {
			return &ValidationError{Name: "review_type", err: fmt.Errorf(`internal: validator failed for field "Review.review_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Rating(); ok {
		if err := review.RatingValidator(v); err != nil {
			return &ValidationError{Name: "rating", err: fmt.Errorf(`internal: validator failed for field "Review.rating": %w`, err)}
		}
	}
	return nil
}

func (_u *ReviewUpdateOne) sqlSave(ctx context.Context) (_node *Review, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(review.Table, review.Columns, sqlgraph.NewFieldSpec(review.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`internal: missing "Review.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, review.FieldID)
		for _, f := range fields {
			if !review.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("internal: invalid field %q for query", f)}
			}
			if f != review.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(review.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReviewType(); ok {
		_spec.SetField(review.FieldReviewType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(review.FieldRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(review.FieldRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(review.FieldComment, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(review.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(review.FieldPhone, field.TypeString)
	}
	if _u.mutation.AdCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.AdTable,
			Columns: []string{review.AdColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ad.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.AdTable,
			Columns: []string{review.AdColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ad.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Review{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{review.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
