// Code generated by ent, DO NOT EDIT.

package internal

import (
	"blindbuy-backend/internal/ad"
	"blindbuy-backend/internal/review"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ReviewCreate is the builder for creating a Review entity.
type ReviewCreate struct {
	config
	mutation *ReviewMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *ReviewCreate) SetCreateTime(v time.Time) *ReviewCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *ReviewCreate) SetNillableCreateTime(v *time.Time) *ReviewCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *ReviewCreate) SetUpdateTime(v time.Time) *ReviewCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *ReviewCreate) SetNillableUpdateTime(v *time.Time) *ReviewCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetReviewType sets the "review_type" field.
func (_c *ReviewCreate) SetReviewType(v review.ReviewType) *ReviewCreate {
	_c.mutation.SetReviewType(v)
	return _c
}

// SetRating sets the "rating" field.
func (_c *ReviewCreate) SetRating(v int) *ReviewCreate {
	_c.mutation.SetRating(v)
	return _c
}

// SetComment sets the "comment" field.
func (_c *ReviewCreate) SetComment(v string) *ReviewCreate {
	_c.mutation.SetComment(v)
	return _c
}

// SetPhone sets the "phone" field.
func (_c *ReviewCreate) SetPhone(v string) *ReviewCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_c *ReviewCreate) SetNillablePhone(v *string) *ReviewCreate {
	if v != nil {
		_c.SetPhone(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ReviewCreate) SetID(v int) *ReviewCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetAdID sets the "ad" edge to the Ad entity by ID.
func (_c *ReviewCreate) SetAdID(id int) *ReviewCreate {
	_c.mutation.SetAdID(id)
	return _c
}

// SetNillableAdID sets the "ad" edge to the Ad entity by ID if the given value is not nil.
func (_c *ReviewCreate) SetNillableAdID(id *int) *ReviewCreate {
	if id != nil {
		_c = _c.SetAdID(*id)
	}
	return _c
}

// SetAd sets the "ad" edge to the Ad entity.
func (_c *ReviewCreate) SetAd(v *Ad) *ReviewCreate {
	return _c.SetAdID(v.ID)
}

// Mutation returns the ReviewMutation object of the builder.
func (_c *ReviewCreate) Mutation() *ReviewMutation {
	return _c.mutation
}

// Save creates the Review in the database.
func (_c *ReviewCreate) Save(ctx context.Context) (*Review, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReviewCreate) SaveX(ctx context.Context) *Review {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReviewCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReviewCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReviewCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := review.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := review.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReviewCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`internal: missing required field "Review.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`internal: missing required field "Review.update_time"`)}
	}
	if _, ok := _c.mutation.ReviewType(); !ok {
		return &ValidationError{Name: "review_type", err: errors.New(`internal: missing required field "Review.review_type"`)}
	}
	if v, ok := _c.mutation.ReviewType(); ok {
		if err := review.ReviewTypeValidator(v); err != nil {
			return &ValidationError{Name: "review_type", err: fmt.Errorf(`internal: validator failed for field "Review.review_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Rating(); !ok {
		return &ValidationError{Name: "rating", err: errors.New(`internal: missing required field "Review.rating"`)}
	}
	if v, ok := _c.mutation.Rating(); ok {
		if err := review.RatingValidator(v); err != nil {
			return &ValidationError{Name: "rating", err: fmt.Errorf(`internal: validator failed for field "Review.rating": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Comment(); !ok {
		return &ValidationError{Name: "comment", err: errors.New(`internal: missing required field "Review.comment"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := review.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`internal: validator failed for field "Review.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ReviewCreate) sqlSave(ctx context.Context) (*Review, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReviewCreate) createSpec() (*Review, *sqlgraph.CreateSpec) {
	var (
		_node = &Review{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(review.Table, sqlgraph.NewFieldSpec(review.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(review.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(review.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.ReviewType(); ok {
		_spec.SetField(review.FieldReviewType, field.TypeEnum, value)
		_node.ReviewType = value
	}
	if value, ok := _c.mutation.Rating(); ok {
		_spec.SetField(review.FieldRating, field.TypeInt, value)
		_node.Rating = value
	}
	if value, ok := _c.mutation.Comment(); ok {
		_spec.SetField(review.FieldComment, field.TypeString, value)
		_node.Comment = value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(review.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if nodes := _c.mutation.AdIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.AdTable,
			Columns: []string{review.AdColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ad.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ad_reviews = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ReviewCreateBulk is the builder for creating many Review entities in bulk.
type ReviewCreateBulk struct {
	config
	err      error
	builders []*ReviewCreate
}

// Save creates the Review entities in the database.
func (_c *ReviewCreateBulk) Save(ctx context.Context) ([]*Review, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Review, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReviewMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReviewCreateBulk) SaveX(ctx context.Context) []*Review {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReviewCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReviewCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
