// Code generated by ent, DO NOT EDIT.

package internal

import (
	"blindbuy-backend/internal/ad"
	"blindbuy-backend/internal/models"
	"blindbuy-backend/internal/review"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	adMixin := models.Ad{}.Mixin()
	adMixinFields0 := adMixin[0].Fields()
	_ = adMixinFields0
	adFields := models.Ad{}.Fields()
	_ = adFields
	// adDescCreateTime is the schema descriptor for create_time field.
	adDescCreateTime := adMixinFields0[0].Descriptor()
	// ad.DefaultCreateTime holds the default value on creation for the create_time field.
	ad.DefaultCreateTime = adDescCreateTime.Default.(func() time.Time)
	// adDescUpdateTime is the schema descriptor for update_time field.
	adDescUpdateTime := adMixinFields0[1].Descriptor()
	// ad.DefaultUpdateTime holds the default value on creation for the update_time field.
	ad.DefaultUpdateTime = adDescUpdateTime.Default.(func() time.Time)
	// ad.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	ad.UpdateDefaultUpdateTime = adDescUpdateTime.UpdateDefault.(func() time.Time)
	// adDescAverageRating is the schema descriptor for average_rating field.
	adDescAverageRating := adFields[6].Descriptor()
	// ad.DefaultAverageRating holds the default value on creation for the average_rating field.
	ad.DefaultAverageRating = adDescAverageRating.Default.(float64)
	// adDescReviewCount is the schema descriptor for review_count field.
	adDescReviewCount := adFields[7].Descriptor()
	// ad.DefaultReviewCount holds the default value on creation for the review_count field.
	ad.DefaultReviewCount = adDescReviewCount.Default.(int)
	// adDescCreatedAt is the schema descriptor for created_at field.
	adDescCreatedAt := adFields[8].Descriptor()
	// ad.DefaultCreatedAt holds the default value on creation for the created_at field.
	ad.DefaultCreatedAt = adDescCreatedAt.Default.(func() time.Time)
	// adDescUpdatedAt is the schema descriptor for updated_at field.
	adDescUpdatedAt := adFields[9].Descriptor()
	// ad.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	ad.DefaultUpdatedAt = adDescUpdatedAt.Default.(func() time.Time)
	// ad.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	ad.UpdateDefaultUpdatedAt = adDescUpdatedAt.UpdateDefault.(func() time.Time)
	// adDescID is the schema descriptor for id field.
	adDescID := adFields[0].Descriptor()
	// ad.IDValidator is a validator for the "id" field. It is called by the builders before save.
	ad.IDValidator = adDescID.Validators[0].(func(int) error)
	reviewMixin := models.Review{}.Mixin()
	reviewMixinFields0 := reviewMixin[0].Fields()
	_ = reviewMixinFields0
	reviewFields := models.Review{}.Fields()
	_ = reviewFields
	// reviewDescCreateTime is the schema descriptor for create_time field.
	reviewDescCreateTime := reviewMixinFields0[0].Descriptor()
	// review.DefaultCreateTime holds the default value on creation for the create_time field.
	review.DefaultCreateTime = reviewDescCreateTime.Default.(func() time.Time)
	// reviewDescUpdateTime is the schema descriptor for update_time field.
	reviewDescUpdateTime := reviewMixinFields0[1].Descriptor()
	// review.DefaultUpdateTime holds the default value on creation for the update_time field.
	review.DefaultUpdateTime = reviewDescUpdateTime.Default.(func() time.Time)
	// review.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	review.UpdateDefaultUpdateTime = reviewDescUpdateTime.UpdateDefault.(func() time.Time)
	// reviewDescRating is the schema descriptor for rating field.
	reviewDescRating := reviewFields[2].Descriptor()
	// review.RatingValidator is a validator for the "rating" field. It is called by the builders before save.
	review.RatingValidator = func() func(int) error {
		validators := reviewDescRating.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(rating int) error {
			for _, fn := range fns {
				if err := fn(rating); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// reviewDescID is the schema descriptor for id field.
	reviewDescID := reviewFields[0].Descriptor()
	// review.IDValidator is a validator for the "id" field. It is called by the builders before save.
	review.IDValidator = reviewDescID.Validators[0].(func(int) error)
}
