// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AdsColumns holds the columns for the "ads" table.
	AdsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "url", Type: field.TypeString, Unique: true},
		{Name: "title", Type: field.TypeString, Nullable: true},
		{Name: "price", Type: field.TypeString, Nullable: true},
		{Name: "category", Type: field.TypeString, Nullable: true},
		{Name: "phone", Type: field.TypeString, Nullable: true},
		{Name: "average_rating", Type: field.TypeFloat64, Default: 0},
		{Name: "review_count", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AdsTable holds the schema information for the "ads" table.
	AdsTable = &schema.Table{
		Name:       "ads",
		Columns:    AdsColumns,
		PrimaryKey: []*schema.Column{AdsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "ad_url",
				Unique:  false,
				Columns: []*schema.Column{AdsColumns[3]},
			},
			{
				Name:    "ad_phone",
				Unique:  false,
				Columns: []*schema.Column{AdsColumns[7]},
			},
			{
				Name:    "ad_category",
				Unique:  false,
				Columns: []*schema.Column{AdsColumns[6]},
			},
			{
				Name:    "ad_created_at",
				Unique:  false,
				Columns: []*schema.Column{AdsColumns[10]},
			},
		},
	}
	// ReviewsColumns holds the columns for the "reviews" table.
	ReviewsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "review_type", Type: field.TypeEnum, Enums: []string{"ad", "seller"}},
		{Name: "rating", Type: field.TypeInt},
		{Name: "comment", Type: field.TypeString, Size: 2147483647},
		{Name: "phone", Type: field.TypeString, Nullable: true},
		{Name: "ad_reviews", Type: field.TypeInt, Nullable: true},
	}
	// ReviewsTable holds the schema information for the "reviews" table.
	ReviewsTable = &schema.Table{
		Name:       "reviews",
		Columns:    ReviewsColumns,
		PrimaryKey: []*schema.Column{ReviewsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "reviews_ads_reviews",
				Columns:    []*schema.Column{ReviewsColumns[7]},
				RefColumns: []*schema.Column{AdsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "review_review_type",
				Unique:  false,
				Columns: []*schema.Column{ReviewsColumns[3]},
			},
			{
				Name:    "review_phone",
				Unique:  false,
				Columns: []*schema.Column{ReviewsColumns[6]},
			},
			{
				Name:    "review_rating",
				Unique:  false,
				Columns: []*schema.Column{ReviewsColumns[4]},
			},
			{
				Name:    "review_create_time",
				Unique:  false,
				Columns: []*schema.Column{ReviewsColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AdsTable,
		ReviewsTable,
	}
)

func init() {
	ReviewsTable.ForeignKeys[0].RefTable = AdsTable
}
