// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Ad is the predicate function for ad builders.
type Ad func(*sql.Selector)

// Review is the predicate function for review builders.
type Review func(*sql.Selector)
